# Generated by Django 6.0.3 on 2026-04-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260326_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a .docx file containing the questions. Existing questions will be wiped and replaced.', null=True, upload_to='question_banks/'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
