# Generated by Django 6.0.3 on 2026-04-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='flashcard_document',
            field=models.FileField(blank=True, help_text='Upload a .docx file for Flashcards (Format: Front: text \\n Back: text). Existing flashcards will be wiped and replaced.', null=True, upload_to='flashcard_banks/'),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
