# Generated by Django 6.0.3 on 2026-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject_flashcard_document_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocationalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Practical Skills', 'Practical Skills'), ('Soft / Digital Skills', 'Soft / Digital Skills')], default='Practical Skills', max_length=50)),
                ('youtube_url', models.URLField(max_length=500)),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-tools)', max_length=50)),
            ],
        ),
    ]
