# Generated by Django 6.0.3 on 2026-05-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_learningcategory_learningtopic_learningprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtopic',
            name='category',
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_topics', to='core.subject'),
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.learningcategory'),
        ),
    ]
